apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: wwa-api-mongodb  # Updated label to match the backend Deployment
spec:
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc
  containers:
  - name: mongodb
    image: mongo:latest
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
