apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4 # Specify a version rather than using 'latest'
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "256Mi" # Define resource requests
              cpu: "0.1"
            limits:
              memory: "1Gi" # Define resource limits
              cpu: "0.5"
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db # Mount path for MongoDB data
      volumes:
        - name: mongodb-storage
          emptyDir: {} # Use emptyDir for demonstration; replace with persistent volume for production
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
