name: MERN Stack CI/CD

on:
  push:
    branches:
      - main
      - backend
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/backend'
        working-directory: backend
        run: npm install

      - name: Run backend tests
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/backend'
        working-directory: backend
        run: npm test

      - name: Install frontend dependencies
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/frontend'
        working-directory: frontend
        run: npm install

      - name: Run frontend tests
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/frontend'
        working-directory: frontend
        run: npm test

      - name: Build frontend
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/frontend'
        working-directory: frontend
        run: npm run build

     
