name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        working-directory: ./WWA-frontend-master
        run: npm install

      - name: Install backend dependencies
        working-directory: ./WWA-backend-master
        run: npm install

      - name: Build Client Docker Image
        working-directory: ./WWA-frontend-master
        run: docker build -t pavanvarikolu/wwafrontend:client-${{github.run_number}} .

      - name: Build Server Docker Image
        working-directory: ./WWA-backend-master
        run: docker build -t pavanvarikolu/wwabackend:server-${{github.run_number}} .

      - name: OWASP Dependency-Check for frontend
        working-directory: ./WWA-frontend-master
        uses: owasp/dependency-check-action@v2

      - name: OWASP Dependency-Check for backend
        working-directory: ./WWA-backend-master
        uses: owasp/dependency-check-action@v2

      - name: Trivy Scan Client Docker Image
        run: docker run --rm -v $(pwd)/WWA-frontend-master:/src -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy pavanvarikolu/wwafrontend:client-${{github.run_number}}

      - name: Trivy Scan Server Docker Image
        run: docker run --rm -v $(pwd)/WWA-backend-master:/src -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy pavanvarikolu/wwabackend:server-${{github.run_number}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images to Docker Hub
        run: |
          docker push pavanvarikolu/wwafrontend:client-${{github.run_number}} || true
          docker push pavanvarikolu/wwabackend:server-${{github.run_number}} || true
